/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;
namespace Alphora.Fastore
{

  [Serializable]
  public partial class LockExpired : Exception, TBase
  {
    private long _LockID;

    public long LockID
    {
      get
      {
        return _LockID;
      }
      set
      {
        __isset.LockID = true;
        this._LockID = value;
      }
    }


    public Isset __isset;
    [Serializable]
    public struct Isset {
      public bool LockID;
    }

    public LockExpired() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I64) {
              LockID = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("LockExpired");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.LockID) {
        field.Name = "LockID";
        field.Type = TType.I64;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(LockID);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("LockExpired(");
      sb.Append("LockID: ");
      sb.Append(LockID);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
