/**
 * Autogenerated by Thrift Compiler (0.9.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Alphora.Fastore
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class OptionalServiceState : TBase
  {
    private ServiceState _serviceState;
    private int _potentialWorkers;

    public ServiceState ServiceState
    {
      get
      {
        return _serviceState;
      }
      set
      {
        __isset.serviceState = true;
        this._serviceState = value;
      }
    }

    public int PotentialWorkers
    {
      get
      {
        return _potentialWorkers;
      }
      set
      {
        __isset.potentialWorkers = true;
        this._potentialWorkers = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool serviceState;
      public bool potentialWorkers;
    }

    public OptionalServiceState() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Struct) {
              ServiceState = new ServiceState();
              ServiceState.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              PotentialWorkers = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("OptionalServiceState");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (ServiceState != null && __isset.serviceState) {
        field.Name = "serviceState";
        field.Type = TType.Struct;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        ServiceState.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (__isset.potentialWorkers) {
        field.Name = "potentialWorkers";
        field.Type = TType.I32;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(PotentialWorkers);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("OptionalServiceState(");
      sb.Append("ServiceState: ");
      sb.Append(ServiceState== null ? "<null>" : ServiceState.ToString());
      sb.Append(",PotentialWorkers: ");
      sb.Append(PotentialWorkers);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
