/**
 * Autogenerated by Thrift Compiler (0.9.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Alphora.Fastore
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class Query : TBase
  {
    private List<byte[]> _rowIDs;
    private List<RangeRequest> _ranges;

    public List<byte[]> RowIDs
    {
      get
      {
        return _rowIDs;
      }
      set
      {
        __isset.rowIDs = true;
        this._rowIDs = value;
      }
    }

    public List<RangeRequest> Ranges
    {
      get
      {
        return _ranges;
      }
      set
      {
        __isset.ranges = true;
        this._ranges = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool rowIDs;
      public bool ranges;
    }

    public Query() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.List) {
              {
                RowIDs = new List<byte[]>();
                TList _list34 = iprot.ReadListBegin();
                for( int _i35 = 0; _i35 < _list34.Count; ++_i35)
                {
                  byte[] _elem36 = null;
                  _elem36 = iprot.ReadBinary();
                  RowIDs.Add(_elem36);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.List) {
              {
                Ranges = new List<RangeRequest>();
                TList _list37 = iprot.ReadListBegin();
                for( int _i38 = 0; _i38 < _list37.Count; ++_i38)
                {
                  RangeRequest _elem39 = new RangeRequest();
                  _elem39 = new RangeRequest();
                  _elem39.Read(iprot);
                  Ranges.Add(_elem39);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("Query");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (RowIDs != null && __isset.rowIDs) {
        field.Name = "rowIDs";
        field.Type = TType.List;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.String, RowIDs.Count));
          foreach (byte[] _iter40 in RowIDs)
          {
            oprot.WriteBinary(_iter40);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (Ranges != null && __isset.ranges) {
        field.Name = "ranges";
        field.Type = TType.List;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, Ranges.Count));
          foreach (RangeRequest _iter41 in Ranges)
          {
            _iter41.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("Query(");
      sb.Append("RowIDs: ");
      sb.Append(RowIDs);
      sb.Append(",Ranges: ");
      sb.Append(Ranges);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
