/**
 * Autogenerated by Thrift Compiler (0.9.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Alphora.Fastore
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class RangeBound : TBase
  {
    private byte[] _Value;
    private bool _Inclusive;
    private byte[] _RowID;

    public byte[] Value
    {
      get
      {
        return _Value;
      }
      set
      {
        __isset.Value = true;
        this._Value = value;
      }
    }

    public bool Inclusive
    {
      get
      {
        return _Inclusive;
      }
      set
      {
        __isset.Inclusive = true;
        this._Inclusive = value;
      }
    }

    public byte[] RowID
    {
      get
      {
        return _RowID;
      }
      set
      {
        __isset.RowID = true;
        this._RowID = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool Value;
      public bool Inclusive;
      public bool RowID;
    }

    public RangeBound() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              Value = iprot.ReadBinary();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.Bool) {
              Inclusive = iprot.ReadBool();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.String) {
              RowID = iprot.ReadBinary();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("RangeBound");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (Value != null && __isset.Value) {
        field.Name = "Value";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteBinary(Value);
        oprot.WriteFieldEnd();
      }
      if (__isset.Inclusive) {
        field.Name = "Inclusive";
        field.Type = TType.Bool;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteBool(Inclusive);
        oprot.WriteFieldEnd();
      }
      if (RowID != null && __isset.RowID) {
        field.Name = "RowID";
        field.Type = TType.String;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteBinary(RowID);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("RangeBound(");
      sb.Append("Value: ");
      sb.Append(Value);
      sb.Append(",Inclusive: ");
      sb.Append(Inclusive);
      sb.Append(",RowID: ");
      sb.Append(RowID);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
