/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;
using Thrift.Transport;
namespace Alphora.Fastore
{

  [Serializable]
  public partial class Repository : TBase
  {
    private int _ColumnID;
    private int _HostID;

    public int ColumnID
    {
      get
      {
        return _ColumnID;
      }
      set
      {
        __isset.ColumnID = true;
        this._ColumnID = value;
      }
    }

    public int HostID
    {
      get
      {
        return _HostID;
      }
      set
      {
        __isset.HostID = true;
        this._HostID = value;
      }
    }


    public Isset __isset;
    [Serializable]
    public struct Isset {
      public bool ColumnID;
      public bool HostID;
    }

    public Repository() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              ColumnID = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              HostID = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("Repository");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.ColumnID) {
        field.Name = "ColumnID";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(ColumnID);
        oprot.WriteFieldEnd();
      }
      if (__isset.HostID) {
        field.Name = "HostID";
        field.Type = TType.I32;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(HostID);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("Repository(");
      sb.Append("ColumnID: ");
      sb.Append(ColumnID);
      sb.Append(",HostID: ");
      sb.Append(HostID);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
