/**
 * Autogenerated by Thrift Compiler (0.9.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Alphora.Fastore
{
  public enum ServiceStatus
  {
    Offline = 1,
    Online = 2,
    Unreachable = 3,
  }
}
