/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Comm_CONSTANTS_H
#define Comm_CONSTANTS_H

#include "Comm_types.h"

namespace fastore { namespace communication {

class CommConstants {
 public:
  CommConstants();

};

extern const CommConstants g_Comm_constants;

}} // namespace

#endif
