/**
 * Autogenerated by Thrift Compiler (0.9.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Comm_constants.h"

namespace fastore { namespace communication {

const CommConstants g_Comm_constants;

CommConstants::CommConstants() {
}

}} // namespace

