/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Server_constants.h"

namespace fastore { namespace server {

const ServerConstants g_Server_constants;

ServerConstants::ServerConstants() {
}

}} // namespace

