PROJDIR = $(HOME)/projects/alphora/Fastore/trunk


CFLAGS += -g -I.. -I../../FastoreClient -I../../FastoreCommunication \
	-I$(PROJDIR)/External/Thrift/src \
	-I/usr/pkg/include

OBJ = 	Wal.o \
	sqlite3/support.o

all: $(OBJ)